/**
 * Dynamic Plugin Type Generator
 * Scans plugin files and generates TypeScript type declarations automatically
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, extname } from "node:path";

const PLUGINS_DIR = join(process.cwd(), "plugins");
const OUTPUT_FILE = join(process.cwd(), "src", "types", "plugin-registry.generated.ts");

interface PluginInfo {
  name: string;
  version: string;
  hasSharedApi: boolean;
  sharedApiType?: string;
  filePath: string;
  isTypeScript: boolean;
}

/**
 * Parse plugin file and extract metadata
 */
function parsePlugin(filePath: string, content: string): PluginInfo | null {
  const isTypeScript = extname(filePath) === ".ts";
  const fileName = filePath.split(/[/\\]/).pop() || "";
  
  // Extract class/export name
  const classMatch = content.match(/export\s+(?:default\s+)?(?:class|interface|const)\s+(\w+)/);
  const exportName = classMatch?.[1] || fileName.replace(/\.(ts|js)$/, "");
  
  // Extract plugin name
  const nameMatch = content.match(/name\s*=\s*["']([^"']+)["']/);
  const name = nameMatch?.[1] || exportName.toLowerCase().replace(/plugin$/i, "");
  
  // Extract version
  const versionMatch = content.match(/version\s*=\s*["']([^"']+)["']/);
  const version = versionMatch?.[1] || "1.0.0";
  
  // Check for getSharedApi
  const hasSharedApi = /getSharedApi\s*\(\s*\)/.test(content) || /getSharedApi:\s*\(/ .test(content);
  
  // Extract API type if present
  let sharedApiType: string | undefined;
  const apiTypeMatch = content.match(/getSharedApi\s*\(\s*\):\s*(\w+Api)/);
  if (apiTypeMatch) {
    sharedApiType = apiTypeMatch[1];
  }
  
  return {
    name,
    version,
    hasSharedApi,
    sharedApiType,
    filePath,
    isTypeScript
  };
}

/**
 * Generate TypeScript declaration content
 */
function generateTypeDeclarations(plugins: PluginInfo[]): string {
  const pluginNames = plugins.map(p => `  | "${p.name}"`).join("\n");
  
  const pluginTypes = plugins.map(p => {
    const apiType = p.sharedApiType || "any";
    return `
export interface ${apiType} {
  name: string;
  version: string;
}

export type ${p.name}Api = ${apiType};`;
  }).join("\n");
  
  const pluginApiTypes = plugins.map(p => {
    const apiType = p.sharedApiType || "any";
    return `  | "${p.name}" ? ${apiType}`;
  }).join("\n");
  
  return `/**
 * AUTO-GENERATED PLUGIN TYPES
 * Generated by scripts/generate-plugin-types.ts
 * DO NOT EDIT MANUALLY
 * Last generated: ${new Date().toISOString()}
 */

${pluginTypes}

// ===========================================
// TYPE REGISTRY
// ===========================================

export type KnownPluginNames = 
${pluginNames};

// ===========================================
// TYPE UTILITIES
// ===========================================

export type PluginApiType<T extends KnownPluginNames> =${pluginApiTypes}
  : any;

export type PluginType<T extends KnownPluginNames> = T extends KnownPluginNames ? IPlugin : never;

// ===========================================
// CONTEXT AUGMENTATION
// ===========================================

declare module "../PluginManager" {
  interface PluginManager {
    /**
     * Get a plugin instance by name
     */
    getPlugin<T extends KnownPluginNames>(name: T): PluginType<T> | undefined;
    
    /**
     * Get the shared API for a plugin
     */
    getSharedApi<T extends KnownPluginNames>(name: T): PluginApiType<T> | undefined;
  }
}
`;
}

/**
 * Scan directory recursively for plugin files
 */
async function scanPlugins(dir: string): Promise<string[]> {
  const plugins: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    
    if (entry.isDirectory()) {
      // Skip node_modules and hidden directories
      if (entry.name !== "node_modules" && !entry.name.startsWith(".")) {
        plugins.push(...(await scanPlugins(fullPath)));
      }
    } else if (entry.isFile()) {
      // Only process .ts and .js files (not .d.ts)
      const ext = extname(entry.name);
      if (ext === ".ts" || ext === ".js") {
        plugins.push(fullPath);
      }
    }
  }
  
  return plugins;
}

/**
 * Main generator function
 */
async function generate() {
  console.log("🔍 Scanning plugins directory...");
  
  try {
    const pluginFiles = await scanPlugins(PLUGINS_DIR);
    console.log(`📦 Found ${pluginFiles.length} plugin files`);
    
    const plugins: PluginInfo[] = [];
    
    for (const filePath of pluginFiles) {
      try {
        const content = await readFile(filePath, "utf-8");
        const pluginInfo = parsePlugin(filePath, content);
        
        if (pluginInfo) {
          plugins.push(pluginInfo);
          const relPath = relative(process.cwd(), filePath);
          console.log(`  ✓ ${pluginInfo.name} v${pluginInfo.version} (${relPath})`);
        }
      } catch (err) {
        const relPath = relative(process.cwd(), filePath);
        console.warn(`  ⚠ Failed to parse ${relPath}: ${err}`);
      }
    }
    
    console.log("\n📝 Generating type declarations...");
    const declarations = generateTypeDeclarations(plugins);
    
    await writeFile(OUTPUT_FILE, declarations, "utf-8");
    
    console.log(`✅ Generated ${OUTPUT_FILE}`);
    console.log(`\n📊 Summary:`);
    console.log(`   - Total plugins: ${plugins.length}`);
    console.log(`   - Plugins with shared API: ${plugins.filter(p => p.hasSharedApi).length}`);
    
  } catch (err) {
    console.error("❌ Error generating types:", err);
    process.exit(1);
  }
}

// Run if called directly
if (process.argv[1] === import.meta.path) {
  generate();
}

export { generate, scanPlugins, parsePlugin };
